apps/installation/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'apps.installation.views',

    url(r'^ports/$', 'ports_page_view', name='ports-page-view'),
    url(r'^ports/(?P<sid>\d+)/$', 'port_page_view', name='port-page',
        kwargs={'url': 'ports'}),
    url(r'^ports/(?P<sid>\d+)/(?P<action>\w+)/$', 'port_page_view', name='port-page-action',
        kwargs={'url': 'ports'}),

    url(r'^ships/$', 'ships_page_view', name='ships-page-view'),
    url(r'^ships/(?P<sid>\d+)/$', 'ship_page_view', name='ship-page',
        kwargs={'url': 'ships'}),
    url(r'^ships/(?P<sid>\d+)/(?P<action>\w+)/$', 'ship_page_view', name='ship-page-action',
        kwargs={'url': 'ships'}),

    url(r'^icebreakers/$', 'icebreakers_page_view', name='icebreakers-page-view'),
    url(r'^icebreakers/(?P<sid>\d+)/$', 'icebreaker_page_view', name='icebreaker-page',
        kwargs={'url': 'icebreakers'}),
    url(r'^icebreakers/(?P<sid>\d+)/(?P<action>\w+)/$', 'icebreaker_page_view', name='icebreaker-page-action',
        kwargs={'url': 'icebreakers'}),

    url(r'^equipments/$', 'equipments_page_view', name='equipments-page-view'),
    url(r'^equipments/(?P<sid>\d+)/$', 'equipment_page_view', name='equipment-page',
        kwargs={'url': 'equipments'}),
    url(r'^equipments/(?P<sid>\d+)/(?P<action>\w+)/$', 'equipment_page_view', name='equipment-page-action',
        kwargs={'url': 'equipments'}),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    (r'^', include('apps.offline.urls', namespace='home')),
    (r'^', include('apps.installation.urls', namespace='installation')),
    (r'^', include('apps.calculation.urls', namespace='calculation')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

apps/installation/models.py
# coding=utf-8
from django.db import models
from jsonfield import JSONField


class UrlGen(object):
    @classmethod
    def urlstr(cls):
        if hasattr(cls, '__name__'):
            s = cls.__name__.lower()
            if s.endswith('y'):
                return '%sies' % s[:-1]

            for end in ['sh', 's', 'x', 'z', 'c']:
                if s.endswith(end):
                    return '%ses' % s
            return '%ss' % s

        return cls.__class__.urlstr()


class Port(models.Model, UrlGen):
    name = models.CharField(u'Название порта', max_length=100)
    picture = models.ImageField(null=True, blank=True, upload_to='ports')

    latitude = models.FloatField(u'Широта', default=0)
    longitude = models.FloatField(u'Долгота', default=0)

    location = models.CharField(u'Местоположение', default='', max_length=100, blank=True)
    navigation = models.CharField(u'Навигация', default='', max_length=100, blank=True)
    ice_period = models.CharField(u'Ледовый период', default='', max_length=100, blank=True)
    surrounding_towns = models.CharField(u'Ближайшие населенные пункты', default='', max_length=100, blank=True)
    railway = models.CharField(u'Железная дорога', default='', max_length=100, blank=True)
    airport = models.CharField(u'Аэропорт', default='', max_length=100, blank=True)
    oil_terminals = models.CharField(u'Наличие нефтеналивных терминалов', default='', max_length=100, blank=True)

    @classmethod
    def get_coordinates(cls, name):
        obj = cls.objects.filter(name=name)
        return [obj.first().latitude, obj.first().longitude]

    def get_picture_url(self):
        if self.picture:
            return self.picture.url
        return '/static/img/default.jpg'

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        app_label = 'installation'
        verbose_name = u'Порт'
        verbose_name_plural = u'Порты'


class Ship(models.Model, UrlGen):
    name = models.CharField(u'Навазние судна', max_length=100)
    picture = models.ImageField(null=True, blank=True, upload_to='ships')

    # тактико-технические характеристики
    displacement = models.FloatField(u'Водоизмещение, т.', default=0, null=True, blank=True)
    load_capacity = models.FloatField(u'Грузоподъёмность чистая, т.', default=0, null=True, blank=True)
    living_space_decks = models.FloatField(u'Полезная площадь палуб, кв. м.', default=0, null=True, blank=True)
    speed_in_ballast = models.FloatField(u'Скорость хода в балласте, узл.', default=0, null=True, blank=True)
    speed_at_full_load = models.FloatField(u'Скорость хода в полном грузу, узл.', default=0, null=True, blank=True)
    length_max = models.FloatField(u'Длина наибольшая, м.', default=0, null=True, blank=True)
    width_max = models.FloatField(u'Ширина наибольшая, м.', default=0, null=True, blank=True)
    draft_ballast = models.FloatField(u'Осадка в балласте, м.', default=0, null=True, blank=True)
    draft_at_full_load = models.FloatField(u'Осадка в полном грузу, м.', default=0, null=True, blank=True)

    # возможности
    staff = models.IntegerField(u'Личный состав, чел.', default=0, null=True, blank=True)
    cars = models.IntegerField(u'Автомобили, ед.', default=0, null=True, blank=True)
    armoured = models.IntegerField(u'Бронетранспортёры, ед.', default=0, null=True, blank=True)
    artillery = models.IntegerField(u'Артиллерия, ед.', default=0, null=True, blank=True)
    tanks = models.IntegerField(u'Танки, ед.', default=0, null=True, blank=True)
    ammunition = models.IntegerField(u'Боеприпасы, т.', default=0, null=True, blank=True)
    food = models.IntegerField(u'Продовольствие, т.', default=0, null=True, blank=True)
    clothing_equipment = models.IntegerField(u'Вещевое имущество, т.', default=0,
                                             null=True, blank=True)
    fuel_in_containers = models.IntegerField(u'Горючее в таре, т.', default=0, null=True, blank=True)

    def get_picture_url(self):
        if self.picture:
            return self.picture.url
        return '/static/img/default.jpg'

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        app_label = 'installation'
        verbose_name = u'Судно'
        verbose_name_plural = u'Суда'


class Icebreaker(models.Model, UrlGen):
    name = models.CharField(u'Навазние судна', max_length=100)
    picture = models.ImageField(null=True, blank=True, upload_to='icebreakers')

    # тактико-технические характеристики
    building_place = models.CharField(u'Место постройки', max_length=100, null=True, blank=True)
    length_max = models.FloatField(u'Длина наибольшая, м.', default=0, null=True, blank=True)
    width_max = models.FloatField(u'Ширина наибольшая, м.', default=0, null=True, blank=True)
    displacement = models.FloatField(u'Водоизмещение, т.', default=0, null=True, blank=True)
    propulsion_power = models.FloatField(u'Пропульсивная мощность, МВт', default=0, null=True, blank=True)
    type_of_appy = models.CharField(u'Тип АППУ', max_length=100, null=True, blank=True)
    speed = models.FloatField(u'Скорость хода, узл.', default=0, null=True, blank=True)
    endurance = models.FloatField(u'Автономность плавания, мес.', default=0, null=True, blank=True)
    ice_passability = models.FloatField(u'Ледопроходимость, м.', default=0, null=True, blank=True)

    def get_picture_url(self):
        if self.picture:
            return self.picture.url
        return '/static/img/default.jpg'

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        app_label = 'installation'
        verbose_name = u'Ледокол'
        verbose_name_plural = u'Ледоколы'


class MilitaryEquipment(models.Model, UrlGen):
    name = models.CharField(u'Наименование техники', max_length=100)
    picture = models.ImageField(null=True, blank=True, upload_to='equipment')

    weight = models.FloatField(u'Масса, т.', default=0, null=True, blank=True)
    length = models.FloatField(u'Длина, мм', default=0, null=True, blank=True)
    width = models.FloatField(u'Ширина, мм', default=0, null=True, blank=True)
    height = models.FloatField(u'Высота, мм', default=0, null=True, blank=True)
    truck_chassis = models.CharField(u'Колёсная формула', max_length=13, null=True, blank=True)
    accumulation_factor = models.CharField(u'Норма размещения пл/пв', max_length=13, null=True, blank=True)

    def get_picture_url(self):
        if self.picture:
            return self.picture.url
        return '/static/img/default.jpg'

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        app_label = 'installation'
        verbose_name = u'Военная техника'
        verbose_name_plural = u'Военная техника'


class Edge(models.Model):
    from_port = models.ForeignKey(Port, related_name='from_port')
    to_port = models.ForeignKey(Port, related_name='to_port')
    dist = models.FloatField(u'Расстояние, км.', default=0)
    path = JSONField(default=[])

    @classmethod
    def get_dist(cls, from_port, to_port):
        obj = cls.objects.filter(from_port=from_port, to_port=to_port)
        if not obj:
            obj = cls.objects.filter(from_port=to_port, to_port=from_port)

        return obj.first().dist

    @classmethod
    def get_path(cls, from_port, to_port):
        obj = cls.objects.filter(from_port=from_port, to_port=to_port)
        if not obj:
            obj = cls.objects.filter(from_port=to_port, to_port=from_port)
            return obj.first().path[::-1]

        return obj.first().path

    def __unicode__(self):
        return u'%s %s to %s = %s km' % ('OK!' if self.path else '',
                                         self.from_port, self.to_port, self.dist)

    class Meta:
        app_label = 'installation'
        verbose_name = u'Расстояние'
        verbose_name_plural = u'Расстояния'

apps/installation/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.installation.models import Port, Ship, Icebreaker, MilitaryEquipment


class PortForm(forms.ModelForm):
    class Meta:
        model = Port
        fields = '__all__'
        exclude = ['picture']


class ShipForm(forms.ModelForm):
    class Meta:
        model = Ship
        fields = '__all__'
        exclude = ['picture']


class IcebreakerForm(forms.ModelForm):
    class Meta:
        model = Icebreaker
        fields = '__all__'
        exclude = ['picture']


class MilitaryEquipmentForm(forms.ModelForm):
    class Meta:
        model = MilitaryEquipment
        fields = '__all__'
        exclude = ['picture']

apps/installation/views.py
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import TemplateView
from django.shortcuts import render_to_response, get_object_or_404, redirect
from apps.installation.models import Port, Ship, Icebreaker, MilitaryEquipment
from django.views.generic.base import View
from apps.installation.forms import PortForm, ShipForm, IcebreakerForm, MilitaryEquipmentForm


class BasePageView(TemplateView):
    model = None

    @staticmethod
    def get_all_data(model):
        data = []
        for obj in model.objects.all():
            data.append({
                'name': obj.name,
                'id': obj.id,
                'picture_url': obj.get_picture_url()
            })
        return data

    def get_context_data(self, **kwargs):
        model = kwargs.get('model')
        if not model:
            raise Exception(u'Model not found')
        return {model.urlstr(): self.get_all_data(model)}

    def get(self, request, *args, **kwargs):
        return render_to_response(self.template_name,
                                  self.get_context_data(model=self.model),
                                  context_instance=RequestContext(request))


class PortsPageView(BasePageView):
    template_name = 'installation/ports.html'
    model = Port


class ShipsPageView(BasePageView):
    template_name = 'installation/ships.html'
    model = Ship


class IcebreakersPageView(BasePageView):
    template_name = 'installation/icebreakers.html'
    model = Icebreaker


class MilitaryEquipmentsPageView(BasePageView):
    template_name = 'installation/equipments.html'
    model = MilitaryEquipment


ports_page_view = PortsPageView.as_view()
ships_page_view = ShipsPageView.as_view()
icebreakers_page_view = IcebreakersPageView.as_view()
equipments_page_view = MilitaryEquipmentsPageView.as_view()


def get_model_by_url(url):
    if url == 'ports':
        return Port
    if url == 'ships':
        return Ship
    if url == 'icebreakers':
        return Icebreaker
    if url == 'equipments':
        return MilitaryEquipment
    return None


class BaseView(TemplateView):
    form_class = None
    template_name = None
    redirect_url = None

    class Action(object):
        SAVE = 'save'
        DELETE = 'delete'

    def get_context_data(self, **kwargs):
        instance = kwargs['instance']
        return {'form': self.form_class(instance=instance),
                'picture_url': '/static/img/default.jpg' if instance is None else instance.get_picture_url(),
                'id': 0 if instance is None else instance.id}

    def get(self, request, *args, **kwargs):
        sid = int(kwargs.get('sid'))
        if not sid:
            return render_to_response(self.template_name,
                                      self.get_context_data(instance=None),
                                      context_instance=RequestContext(request))

        model = get_model_by_url(kwargs.get('url'))
        obj = model.objects.get(id=sid)
        if obj is None:
            raise Exception(u'port with id = %s do not exists' % str(sid))

        return render_to_response(self.template_name,
                                  self.get_context_data(instance=obj),
                                  context_instance=RequestContext(request))

    def post(self, request, *args, **kwargs):
        sid = int(request.POST['id'])
        instance = None
        if sid:
            instance = get_object_or_404(get_model_by_url(kwargs.get('url')), id=sid)

        if kwargs.get('action') == self.Action.DELETE:
            if instance:
                instance.delete()
            return redirect(reverse('installation:' + self.redirect_url))

        form = self.form_class(request.POST, instance=instance)
        if form.is_valid():
            if kwargs.get('action') == self.Action.SAVE:
                form.save()
            else:
                raise Exception(u'Don\'t know action %s' % kwargs.get('action'))

            return redirect(reverse('installation:' + self.redirect_url))

        return render_to_response(self.template_name,
                                  {'form': form,
                                   'picture_url': '' if instance is None else instance.get_picture_url(),
                                   'id': 0 if instance is None else instance.id},
                                  context_instance=RequestContext(request))


class PortPageView(BaseView):
    template_name = 'installation/port.html'
    form_class = PortForm
    redirect_url = 'ports-page-view'


class ShipPageView(BaseView):
    template_name = 'installation/ship.html'
    form_class = ShipForm
    redirect_url = 'ships-page-view'


class IcebreakerPageView(BaseView):
    template_name = 'installation/icebreaker.html'
    form_class = IcebreakerForm
    redirect_url = 'icebreakers-page-view'


class MilitaryEquipmentPageView(BaseView):
    template_name = 'installation/equipment.html'
    form_class = MilitaryEquipmentForm
    redirect_url = 'equipments-page-view'


port_page_view = PortPageView.as_view()
ship_page_view = ShipPageView.as_view()
icebreaker_page_view = IcebreakerPageView.as_view()
equipment_page_view = MilitaryEquipmentPageView.as_view()

templates/installation/equipment.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 47px;">
        <div class="row content-header" style="text-align: center;">
            <h3>{{ form.name.value }}</h3>
        </div>
        <div class="row" style="padding-top: 10px;">
            <div class="col-lg-8">
                <table class="table">
                    <thead>
                        <h4>Характеристики</h4>
                    </thead>
                    <tbody>
                        {% include 'installation/fields/_input.html' with form_field=form.weight %}
                        {% include 'installation/fields/_input.html' with form_field=form.length %}
                        {% include 'installation/fields/_input.html' with form_field=form.width %}
                        {% include 'installation/fields/_input.html' with form_field=form.height %}
                        {% include 'installation/fields/_input.html' with form_field=form.truck_chassis %}
                        {% include 'installation/fields/_input.html' with form_field=form.accumulation_factor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <img src="{{ picture_url }}" width="100%;" height="100%;" alt="Картинки пока что нет"/>
            </div>
        </div>
    </div>
{% endblock %}

templates/installation/equipments.html
{% extends 'base.html' %}
{% load static %}

{% block css_extra %}
    <link rel="stylesheet" href="{% static 'css/calculation.css' %}">
{% endblock %}

{% block content %}
    <div class="page-panel">
        <div class="page-panel-inner" style="margin-top: 10px;">
            {% for equipment in militaryequipments %}
                <div class="pure-form table-cell">
                    <a href="{% url 'installation:equipment-page' equipment.id %}">
                        <img src="{{ equipment.picture_url }}" width="200px;" height="150px;"/>
                        <h5>{{ equipment.name }}</h5>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/installation/icebreaker.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 47px;">
        <div class="row content-header" style="text-align: center;">
            <h3>{{ form.name.value }}</h3>
        </div>
        <div class="row" style="padding-top: 10px;">
            <div class="col-lg-8">
                <table class="table">
                    <thead>
                        <h4>Характеристики</h4>
                    </thead>
                    <tbody>
                        {% include 'installation/fields/_input.html' with form_field=form.building_place %}
                        {% include 'installation/fields/_input.html' with form_field=form.length_max %}
                        {% include 'installation/fields/_input.html' with form_field=form.width_max %}
                        {% include 'installation/fields/_input.html' with form_field=form.displacement %}
                        {% include 'installation/fields/_input.html' with form_field=form.propulsion_power %}
                        {% include 'installation/fields/_input.html' with form_field=form.type_of_appy %}
                        {% include 'installation/fields/_input.html' with form_field=form.speed %}
                        {% include 'installation/fields/_input.html' with form_field=form.endurance %}
                        {% include 'installation/fields/_input.html' with form_field=form.ice_passability %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <img src="{{ picture_url }}" width="100%;" height="100%;" alt="Картинки пока что нет"/>
            </div>
        </div>
    </div>
{% endblock %}

templates/installation/icebreakers.html
{% extends 'base.html' %}
{% load static %}

{% block css_extra %}
    <link rel="stylesheet" href="{% static 'css/calculation.css' %}">
{% endblock %}

{% block content %}
    <div class="page-panel">
        <div class="page-panel-inner" style="margin-top: 10px;">
            {% for icebreaker in icebreakers %}
                <div class="pure-form table-cell">
                    <a href="{% url 'installation:icebreaker-page' icebreaker.id %}">
                        <img src="{{ icebreaker.picture_url }}" width="200px;" height="150px;"/>
                        <h5>{{ icebreaker.name }}</h5>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/installation/port.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 47px;">
        <div class="row content-header" style="text-align: center;">
            <h3>{{ form.name.value }}</h3>
        </div>
        <div class="row" style="padding-top: 10px;">
            <div class="col-lg-8">
                <table class="table">
                    <thead>
                        <h4>Информация</h4>
                    </thead>
                    <tbody>
                        {% include 'installation/fields/_input.html' with form_field=form.latitude %}
                        {% include 'installation/fields/_input.html' with form_field=form.longitude %}
                        {% include 'installation/fields/_input.html' with form_field=form.location %}
                        {% include 'installation/fields/_input.html' with form_field=form.navigation %}
                        {% include 'installation/fields/_input.html' with form_field=form.ice_period %}
                        {% include 'installation/fields/_input.html' with form_field=form.surrounding_towns %}
                        {% include 'installation/fields/_input.html' with form_field=form.railway %}
                        {% include 'installation/fields/_input.html' with form_field=form.airport %}
                        {% include 'installation/fields/_input.html' with form_field=form.oil_terminals %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <img src="{{ picture_url }}" width="100%;" height="100%;" alt="Картинки пока что нет"/>
            </div>
        </div>
    </div>
{% endblock %}

templates/installation/ports.html
{% extends 'base.html' %}
{% load static %}

{% block css_extra %}
    <link rel="stylesheet" href="{% static 'css/calculation.css' %}">
{% endblock %}

{% block content %}
    <div class="page-panel">
        <div class="page-panel-inner" style="margin-top: 10px;">
            {% for port in ports %}
                <div class="pure-form table-cell">
                    <a href="{% url 'installation:port-page' port.id %}">
                        <img src="{{ port.picture_url }}" width="200px;" height="150px;"/>
                        <h5>{{ port.name }}</h5>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/installation/ship.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 47px;">
        <div class="row content-header" style="text-align: center;">
            <h3>{{ form.name.value }}</h3>
        </div>
        <div class="row" style="padding-top: 10px;">
            <div class="col-lg-4">
                <table class="table">
                    <thead>
                        <h4>Тактико-технические характеристики</h4>
                    </thead>
                    <tbody>
                        {% include 'installation/fields/_input.html' with form_field=form.displacement %}
                        {% include 'installation/fields/_input.html' with form_field=form.load_capacity %}
                        {% include 'installation/fields/_input.html' with form_field=form.living_space_decks %}
                        {% include 'installation/fields/_input.html' with form_field=form.speed_in_ballast %}
                        {% include 'installation/fields/_input.html' with form_field=form.speed_at_full_load %}
                        {% include 'installation/fields/_input.html' with form_field=form.length_max %}
                        {% include 'installation/fields/_input.html' with form_field=form.width_max %}
                        {% include 'installation/fields/_input.html' with form_field=form.draft_ballast %}
                        {% include 'installation/fields/_input.html' with form_field=form.draft_at_full_load %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <img src="{{ picture_url }}" width="100%;" height="100%;" alt="Картинки пока что нет"/>
            </div>
            <div class="col-lg-4">
                <table class="table">
                    <thead>
                        <h4>Возможности</h4>
                    </thead>
                    <tbody>
                        {% include 'installation/fields/_input.html' with form_field=form.staff %}
                        {% include 'installation/fields/_input.html' with form_field=form.cars %}
                        {% include 'installation/fields/_input.html' with form_field=form.armoured %}
                        {% include 'installation/fields/_input.html' with form_field=form.artillery %}
                        {% include 'installation/fields/_input.html' with form_field=form.tanks %}
                        {% include 'installation/fields/_input.html' with form_field=form.ammunition %}
                        {% include 'installation/fields/_input.html' with form_field=form.food %}
                        {% include 'installation/fields/_input.html' with form_field=form.clothing_equipment %}
                        {% include 'installation/fields/_input.html' with form_field=form.fuel_in_containers %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/installation/ships.html
{% extends 'base.html' %}
{% load static %}

{% block css_extra %}
    <link rel="stylesheet" href="{% static 'css/calculation.css' %}">
{% endblock %}

{% block content %}
    <div class="page-panel">
        <div class="page-panel-inner" style="margin-top: 10px;">
            {% for ship in ships %}
                <div class="pure-form table-cell">
                    <a href="{% url 'installation:ship-page' ship.id %}">
                        <img src="{{ ship.picture_url }}" width="200px;" height="150px;"/>
                        <h5>{{ ship.name }}</h5>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}